server:
  port: 8081

hello:
  name: guang
  age: 27
  ext:
    prop-a: PropA
    prop-b: false

spring:
  datasource:
    url: jdbc:sqlite:test.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: true
#    generate-ddl: true